import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import LoginBtn from './LoginBtn';
import LogOutBtn from './LogOutBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth].js';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  if (session) {
    console.log(session);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            EFUB Forum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <Link href="/register">Register</Link>
          {session ? (
            <span>
              {session.user.name} <LogOutBtn />
            </span>
          ) : (
            <LoginBtn />
          )}
        </div>

        {children}
      </body>
    </html>
  );
}
